services:
  api-minecraftrcon-nodejs:
    container_name: api-minecraftrcon-nodejs
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - RCON_HOST=mc
      - RCON_PORT=25575
      - RCON_PASSWORD=secret
    ports:
      - "3000:3000"
